name: writdle
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  intl: ^0.20.2
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  lucide_icons: ^0.257.0
  fl_chart: ^1.0.0
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/WR-Logo-1.jpg
    - assets/icon/w-logo-image_332120.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/w-logo-image_332120.jpg"
  background_color: "#000000FF"