// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXVhiSmAooSqKlyQngn7BEL1DWx9_Qgws',
    appId: '1:28297846168:web:d5cd749aa9e1d827c2dfed',
    messagingSenderId: '28297846168',
    projectId: 'writdle',
    authDomain: 'writdle.firebaseapp.com',
    storageBucket: 'writdle.firebasestorage.app',
    measurementId: 'G-WQ9P14Y1ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEws1ndVtpzJyWPMypgmqFJ5LgDdQ6kdc',
    appId: '1:28297846168:android:fb9d8216e8fe06f3c2dfed',
    messagingSenderId: '28297846168',
    projectId: 'writdle',
    storageBucket: 'writdle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTOl9-BvUyOybHv_4zmwNL5h2pzW6ghI0',
    appId: '1:28297846168:ios:5e9ddc26fc7e52d3c2dfed',
    messagingSenderId: '28297846168',
    projectId: 'writdle',
    storageBucket: 'writdle.firebasestorage.app',
    iosBundleId: 'com.example.writdle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTOl9-BvUyOybHv_4zmwNL5h2pzW6ghI0',
    appId: '1:28297846168:ios:5e9ddc26fc7e52d3c2dfed',
    messagingSenderId: '28297846168',
    projectId: 'writdle',
    storageBucket: 'writdle.firebasestorage.app',
    iosBundleId: 'com.example.writdle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXVhiSmAooSqKlyQngn7BEL1DWx9_Qgws',
    appId: '1:28297846168:web:ae508f50237a2d3bc2dfed',
    messagingSenderId: '28297846168',
    projectId: 'writdle',
    authDomain: 'writdle.firebaseapp.com',
    storageBucket: 'writdle.firebasestorage.app',
    measurementId: 'G-FE2G7V0YBH',
  );

}